### ISSUE TITLE
Remove unmaintained plugins and configs

### ISSUE THREAD

**Issue by blyedev** [stylelint/awesome-stylelint#78]
### Describe the documentation issue

The following plugins and configs seem to either not be maintained or be abandoned completely.

#### These only have minor issues like lack of 16 version but seem to be somewhat alive
- [stylelint-config-idiomatic-order](https://github.com/ream88/stylelint-config-idiomatic-order) - Maintenance issues ream88/stylelint-config-idiomatic-order#83
- [stylelint-csstree-validator](https://github.com/csstree/stylelint-validator) - csstree/stylelint-validator#59
- [codeclimate-stylelint](https://github.com/gilbarbara/codeclimate-stylelint) - last commit 3 years ago gilbarbara/codeclimate-stylelint#52

#### These seem to be fully dead
- [stylelint-config-prettier](https://www.npmjs.com/package/stylelint-config-prettier) - Deprecated and unmaintained prettier/stylelint-config-prettier#140
- [stylelint-config-rational-order](https://github.com/constverum/stylelint-config-rational-order) - last commit 5 years ago constverum/stylelint-config-rational-order#39
- [stylelint-no-nested-media](https://www.npmjs.com/package/stylelint-no-nested-media) - arguably not that useful and: dkrnl/stylelint-no-nested-media#1
- [stylelint-no-unused-selectors](https://www.npmjs.com/package/stylelint-no-unused-selectors) - last commit 3 years ago nodaguti/stylelint-no-unused-selectors#634
- [stylelint-plugin-ecss](https://www.npmjs.com/package/stylelint-plugin-ecss) - this plugin is so rarely used I couldn't find an issue asking it to be updated
- [stylelint-value-no-exposed-custom-properties](https://www.npmjs.com/package/stylelint-value-no-exposed-custom-properties) - denisraslov/stylelint-value-no-exposed-custom-properties#4
- [stylelint-rscss](https://www.npmjs.com/package/stylelint-rscss) - Last commit is 8 years ago and while it still might partially work I don't think it's good to recommend it to new users
- [stylelint-a11y](https://www.npmjs.com/package/stylelint-a11y) - it seems to have forks but it's definetly dead itself YozhikM/stylelint-a11y#65

### What solution would you like to see?

While I personally would delete at least all fully dead plugins as in my opinion quality outweighs quantity in this specific guide I realize some of those may still be revived in the coming years and so other maintainers may vote to keep them.

I was simply evaluating the ecosystem and decided I might as well let you know what I found while I did.

**Comment by blyedev** [comment]
I have deleted some of the proposed plugins in #79 but only the ones I was sure the community would agree should go.

Please keep this issue open as an RFC

The following are still up for debate:

- [stylelint-config-idiomatic-order](https://github.com/ream88/stylelint-config-idiomatic-order) - Maintenance issues ream88/stylelint-config-idiomatic-order#83
- [stylelint-csstree-validator](https://github.com/csstree/stylelint-validator) - csstree/stylelint-validator#59
- [codeclimate-stylelint](https://github.com/gilbarbara/codeclimate-stylelint) - last commit 3 years ago gilbarbara/codeclimate-stylelint#52

**Comment by Mouvedia** [comment]
> The following are still up for debate:
> 
> * [stylelint-config-idiomatic-order](https://github.com/ream88/stylelint-config-idiomatic-order) - Maintenance issues [Library maintenance  ream88/stylelint-config-idiomatic-order#83](https://github.com/ream88/stylelint-config-idiomatic-order/issues/83)

@ream88 should relinquish the maintenance to someone else.
Or someone—e.g. julienw—should fork it in the meantime.

> * [stylelint-csstree-validator](https://github.com/csstree/stylelint-validator) - [Stylelint 16 support csstree/stylelint-validator#59](https://github.com/csstree/stylelint-validator/pull/59)

stylelint/stylelint#8163 and stylelint/stylelint#8133 have been filled hence it can removed.

> * [codeclimate-stylelint](https://github.com/gilbarbara/codeclimate-stylelint) - last commit 3 years ago [Support stylelint 14 and stylelint-config-standard-scss gilbarbara/codeclimate-stylelint#52](https://github.com/gilbarbara/codeclimate-stylelint/issues/52)

[Code Climate is now Qlty Software.](https://codeclimate.com/blog/code-climate-quality-is-now-qlty-software)
i.e. https://github.com/codeclimate/codeclimate redirects to https://github.com/qltysh/qlty

Hence https://github.com/qltysh/qlty/blob/main/plugins/linters/stylelint/plugin.toml#L28-L29 is more relevant than gilbarbara/codeclimate-stylelint.

**Comment by jeddy3** [comment]
Thank you both for doing the legwork to identify the unmaintained things.

Feel free to open a PR to remove them.
